### ISSUE TITLE
CString 관련 에러

### ISSUE THREAD

**Issue by jhh0712** [jhh0712/IOT-SECURITY-TEST-PLATFORM#10]
![image](https://user-images.githubusercontent.com/25245081/29350094-0b252682-8298-11e7-8003-cda1dd8e1a58.png)

TestServer 쪽에서 CString의 += 연산에서 해당에러 발생합니다.
이 에러는 발생안할때도 있지만 매우 높은확률로 발생하여 도움이 필요합니다.

**Comment by Kim-Hyun-Seok** [comment]
에러가 발생할때도 있고 발생안할때도 있으면 
내 생각에는 자동으로 메모리가 할당될때 겹치는 부분이 간혹 발생하는거 같음
CString 을 무조건 써야되는 상황이아니면
char 배열선언해서 사용하면되지않나..싶은데
아니면 동적메모리할당을 해주거나

**Comment by andrew9790** [comment]
파이 쪽에서도 간혹  메모리 할당에러가 있는데 
valgrind 프로그램 써서 디버깅 해볼 시 메모리가 어떻게 할당되고 누출이나 손실이 어떻게 발생되는지 찾아준다고 합니다. 한번 찾아보겟습니다.

**Comment by jhh0712** [comment]
근데 왜 이프로그램에서만 메모리가 겹치거나 하는 이상현상이 발생할까요....
CString += 연산은 정말 많이사용하는 다른 프로그램에서는 전혀발생하지 않았었습니다.
CString에다가 형변환했을때도 그렇고 CString 자체적으로 문제가 발생하는것 같습니다.

**Comment by jhh0712** [comment]
해결완료 되었습니다. RSA쪽 malloc 문제로 확인되었습니다.
