### ISSUE TITLE
README.MD 수정 바랍니다.

### ISSUE THREAD

**Issue by jhh0712** [jhh0712/IOT-SECURITY-TEST-PLATFORM#13]
계획바뀐것을 기반으로 자세하게 수정바랍니다.
(Bro IDS 바뀐사항, 라즈베리파이쪽에 pcap 얹을 수 있는지와 그내용, 윈도우에 Winpcap, 전체적 내용수정
키관리서버 내용추가)

**Comment by jhh0712** [comment]
전체적으로 수정이 필요합니다. 
우선 프로젝트 소개부분 내용 -> 두가지버전에 대한 설명(암호화버전, IDS + 암호화버전)
라즈베리파이 -> 무선랜, 이더넷 설정 두가지
Bro IDS -> 제거 후 IDS -> Libpcap, Winpcap 추가 

사용법 라즈베리파이 -> 암호화 버전/ IDS버전 나누기
윈도우서버 -> Mysql 라이브러리 추가 내용, Winpcap 라이브러리 추가내용 (암호화/IDS버전 나눠서)

프로젝트 마무리후 공격 실험 내용도 들어가야할것 같음.

**Comment by andrew9790** [comment]
[README.zip](https://github.com/jhh0712/IOT-SECURITY-TEST-PLATFORM/files/1301704/README.zip)

시스템에 대한 설명 변경과 라즈베리파이 내 고정 ip 설정 메뉴얼 추가했습니다.
mysql과 안드로이드 스튜디오 설치 내용에 대해 부족한 점이 있는 것 반영하여 좀더 상세히 작성했고
pacp 라이브러리 추가 방법 및 IDS 내용 변경 했습니다.
공격실험에 대한 내용은 시나리오 논의 후 추가해야 할것 같습니다.

**Comment by andrew9790** [comment]
죄송합니다 라즈베리파이 mysql과 관련 라이브러리 설치내용이 빠졌네요
[README.zip](https://github.com/jhh0712/IOT-SECURITY-TEST-PLATFORM/files/1302672/README.zip)
해당 파일로 확인 바랍니다.
