### ISSUE TITLE
AES 소스코드 주석 작성 바랍니다.

### ISSUE THREAD

**Issue by jhh0712** [jhh0712/IOT-SECURITY-TEST-PLATFORM#14]
현재 깃프로젝트의 서버쪽 소스코드 다운로드하여 해당 AES 헤더파일 주석 작성바랍니다.

**Comment by rudehdqor** [comment]
[AES.zip](https://github.com/jhh0712/IOT-SECURITY-TEST-PLATFORM/files/1301673/AES.zip)
