### ISSUE TITLE
마무리 지어야할 것들 목록

### ISSUE THREAD

**Issue by jhh0712** [jhh0712/IOT-SECURITY-TEST-PLATFORM#16]
1. README.md 내용추가
- 공격실험 , 프로젝트 소개에 상세내용 추가 및 전체적인 오탈자 검사와 부족한내용 추가

2. IDS
- 비정상탐지 특정 룰 만들어서 각각의 IDS에서 탐지하기

3. 소스코드 정리
- 주석정리, 소스코드 정리

4. 결과보고서 내용추가
- 사진, 결과 PT 등 더 있으면 좋음

5. AES 암호화 버전에서 소켓통신 시 데이터 값 튀는것 잡기

6. 시연동영상 제작 3분이내

7. 서버 기능추가
- 서버에 추가되었으면 하는 기능(개인적으로 소켓통신부분을 좀 더 다듬고 싶음)
ex) 접속 사용자 목록 및 서버에서 해당 사용자 접속끊기기능 같은것.

8. 라이센스 관련 내용파일(?) 추가

**Comment by andrew9790** [comment]
공격실험은 ettercap  이용해서 MITM공격 진행하고 Readme 파일에 공격실험 진행하는과정 추가하는거로 하고 소스코드 수정해서 RULE적용후 탐지하는거 적용하고 주석정리 마무리하면 될거고.. 오탈자 및 상세내용 추가할거 최대한 빨리 추가하는 것으로 하겠습니다.
