### ISSUE TITLE
키관리서버 적용방안

### ISSUE THREAD

**Issue by jhh0712** [jhh0712/IOT-SECURITY-TEST-PLATFORM#2]
키 관리, 생성, 분배 어떻게 구현할지 구상필요.

**Comment by Kim-Hyun-Seok** [comment]
키 관리 서버를 하나 구성해서 RSA 암호화로 데이터 암/복호화 후 키 관리하는 방식

키 관리 서버 -> 암호화/복호화 알고리즘 동작하는 서버/클라이언트에 각각 송수신하는 부분 구현해서
기존 통신과는 별개로 키 관리 서버와 별도로 통신하는 방식으로 수정
(송수신받은 키로 암/복호화 수행하도록)

**Comment by Kim-Hyun-Seok** [comment]
http://daitso.kds.co.kr/27632/
참조
