### ISSUE TITLE
라이선스 충돌 문제

### ISSUE THREAD

**Issue by andrew9790** [jhh0712/IOT-SECURITY-TEST-PLATFORM#4]
현재 MySQL을 이용해 데이터베이스설계,
BRO를 이용한 IDS구축을 예정 중 입니다

MYSQL -> https://dev.mysql.com/downloads/windows/
BRO -> https://www.bro.org/

올린 링크에 따르면 MYSQL은 GPL2라이선스이고 BRO는 BSD라이선스인 것으로 확인됩니다.
서로 라이선스 충돌우려가 있으니 더 자세한 사항에 대한 검토 및 대체 오픈소스 사용이 필요하다고 생각합니다.

**Comment by jhh0712** [comment]
라이선스 관해서는 좀 더 알아봐야함.
오리엔테이션에서 들은 블랙덕 프로그램을 사용해보고도 확신이 안생기면
직접 전화를 해서 물어봐야 할것 같음.

[블랙덕 프로텍스 클라이언트](http://protex.blackducksoftware.co.kr)

**Comment by andrew9790** [comment]
결론적으론 MYSQL과 BRO라이센스로 만든 프로그램의 라이선스 충돌은 크게 문제가 없다고 하시는거 같습니다.  혹시라도 문제가 생길것 같다면 PostgreSQL로 대체하는것도 방법이라고 하십니다.

연지영 멘토님 전문입니다. 

안녕하세요. 
OSS 개발자대회의 라이선스 멘토 연지영입니다. 
 
문의주신 내용들이 대부분 개발 환경에 대한 것으로 보입니다.
개발 프로그램들은 개발 환경의 라이선스 영향을 받지 않습니다. 
따라서 개발자가 원한다면 개발된 프로그램은 개발환경과 관계 없이 독자적인 프로그램으로서 임의로 라이선스를 적용할 수 있습니다.
즉, 안드로이드 스튜디오에서 개발된 애플리케이션은 안드로이드 스튜디오의 라이선스와 관계 없습니다. 안드로이드 스튜디오 뿐만 아니라 비주얼 스튜디오도 마찬가지입니다.
덧붙히면 개발 환경이 오픈소스 라이선스 전환된다면 사람들은 개발 환경 자체를 수정, 복제, 사용, 배포하는 것이 가능해지는 것입니다.
 
이러한 이유로 'My-SQL(GPL)'과 'VS(BSD)로 개발한 프로그램'의 라이선스 문제는 발생하지 않을 것 같습니다. 

추가로 현재로는 구현을 위해 사용할 프로그램과 구현할 프로그램, My-SQL을 사용한다 정도의 내용을 파악할 수 있습니다.
지금 상황에서 보이는 특별한 OSS 라이선스 문제는 전혀 없습니다. 
다만 오픈소스 라이선스로 인하여 문제가 발생할지를 확인하기 위해선 SW 프로그램의 구조를 살펴봐야 합니다.
 
메일로 파악하기로는 애플리케이션을 개발할 때 OSS 프로그램을 사용하지 않은 것 같은데, 혹시 OSS 프로그램을 사용하여 프로그램을 개발했다면 라이선스 목록을 작성하시고 그것의 연결 방식을 기재해서 주시면 문제가 있을지 확인해드릴 수 있을 것 같습니다. 
(소스코드로 결합, Dynamic or Static Linking, 소켓 통신, Pipe 등등) 
 
또한 My-SQL과 모바일 애플리케이션은 어떠한 방식으로 통신되나요? 배포할 때 분리하여 배포하는 것이 가능한가요? 
우선 개발한 프로그램과 My-SQL이 분리 배포를 될 수 있고, 사용자(수취인)가 직접 My-SQL을 다운받아 개발 프로그램과 연결하여 사용할 수 있다면 걱정하실 것은 없습니다.

국내 자료들은 My-SQL과 같은 GPL 저작물을 소켓, 파이프, command-line argument 등의 통신방법으로 사용한다면 문제가 발생하지 않을 것이라고 소개하지만 이 부분에 대해선 다양한 이견들이 존재하고 있습니다.
FSF에 따르면(GPL 라이선스의 재단) 소켓이나 파이프 등의 방식으로 애플리케이션과 통신하다면 큰 범위에서 larger work가 될 수 있기 때문에 어플리케이션에 GPL이 적용되어 소스코드 공개를 해야할 수도 있으며, 
만일 애플리케이션에 OSS가 사용되었다면 GPL과의 라이선스 충돌 문제(상충)문제도 살펴보아야 할 것입니다.
