### ISSUE TITLE
통신 데이터 관련 

### ISSUE THREAD

**Issue by jhh0712** [jhh0712/IOT-SECURITY-TEST-PLATFORM#6]
통신데이터를 임의의 값으로 해서 보내려고 하는데

어떤 식으로 데이터를 보내는게 좋을지 의견을 묻습니다.

제가 생각한것은 라즈베리파이에서 16바이트를 다양한 형으로 해서 일정 범위내의 값으로

랜덤하게 보내려고 하는데 더 좋은 아이디어가 있으시면 코멘트 부탁드립니다.

**Comment by Kim-Hyun-Seok** [comment]
통신데이터의 크기를 어느것으로 딱 지정해서 실험하면 안됨
(다양한 데이터의 크기가 가능해야함)
-> 보안 실험 플랫폼이기 때문에 대상 시스템이 어떤 시스템이던간에 실험이 가능해야함
(실험중인 사물인터넷 테스트베드는 16바이트로 고정해서 통신하지만 그 시스템에만 맞추어서 사용할 수는 없음)

*다양한 데이터 크기라기보다는 데이터의 크기에 제한을 받으면 안됨
(후에 암호화 하는 부분은 나중에 고민하고 먼저 데이터 크기에 제한받지 않는 쪽으로 진행)

**Comment by jhh0712** [comment]
그렇다면 라즈베리파이에서 데이터 크기를 사용자가 직접 지정할 수 있도록 가이드를 제공하는게 나을까요?

**Comment by Kim-Hyun-Seok** [comment]
그런쪽보다는 최대 데이터 크기를 제한하는게 더 효율적일거 같음.
(개발하는 쪽이나 사용하는 쪽이나)

**Comment by jhh0712** [comment]
그럼 보내는 데이터를 가변적으로 지정해놓고 사용자가 들어가는 데이터를 수정할 수 있게 가이드를 제공 하면 될 것 같네요.
그렇게 되면 다시 처음으로 돌아와서 테스트 플랫폼에서 보내는 초기 데이터값과 크기는 어떻게 해야할까요? 추후 IDS에서도 데이터값을 분석하게 된다면 어떠한 가이드가 필요하지 않을까 싶습니다.

**Comment by Kim-Hyun-Seok** [comment]
테스트 플랫폼도 초기 데이터값이랑 크기는 최대값을 제한해놓고 최초에는 랜덤값으로 통신을 하다가 
추후에 IDS적용을 하고 나면 데이터 분석이 필요하니까
그 때 tesim을 올리던 스마트홈을 올려서 실험하면 될거 같은데
전체적으로 일단 암호화는 배제를하고 진행을 하는 쪽으로..
