### ISSUE TITLE
TestAndroid 초안 완성

### ISSUE THREAD

**Issue by jhh0712** [jhh0712/IOT-SECURITY-TEST-PLATFORM#8]
안드로이드 초안이 완성되었습니다.
테스트 후 버그나 수정사항있으면 코멘트 부탁드립니다.

추가로 현재 안드로이드 TextView에서 \t 으로 출력문자 정렬 시
1자리수 , 2자리수, 3자리수에 대한 문자정렬이 제대로 이루어지지 않습니다.
해결방안을 아시는 분 코멘트 부탁드립니다.

**Comment by jhh0712** [comment]
저것도 안되네요.. ㅠ

**Comment by Kim-Hyun-Seok** [comment]
msg2 = String.format("%d\t\t", data[i]);    //msg2 String에 Ascii 형태로 데이터 대입
  msg2 += String.format("%d\t\t", data[i]);   //msg2 String에 Ascii 데이터 추가

여기서 %d\t\t 이런식으로하지말고 \t를 변수화 시켜서 string 형식이니까 %d형뒤에 더하는식으로 처리하면?

**Comment by jhh0712** [comment]
msg2 += String.format("%d"+getString(R.string.tab), data[i]); 
이렇게해서 했는데 안됩니다 ,,
