### ISSUE TITLE
라즈베리파이 클라이언트 주석

### ISSUE THREAD

**Issue by jhh0712** [jhh0712/IOT-SECURITY-TEST-PLATFORM#9]
주석작성 바랍니다.

[TestClient.zip](https://github.com/jhh0712/IOT-SECURITY-TEST-PLATFORM/files/1207807/TestClient.zip)

**Comment by rudehdqor** [comment]
[TestClient.zip](https://github.com/jhh0712/IOT-SECURITY-TEST-PLATFORM/files/1213956/TestClient.zip)
